version: '3.2'
services:
  plugin:
    image: arcaflow-uperf
    command: "-s uperf -f /plugin/input/netperf.yaml"
    build: .
    networks:
      - cluster_network
    links:
      - "server"
    depends_on:
      - "server"
    volumes:
      - ./input:/plugin/input:z
  server:
    image: arcaflow-uperf
    command: "-s uperf_server -f /plugin/input/server_input.yaml"
    build: .
    ports:
      - 20000:20000
    networks:
      - cluster_network
    volumes:
      - ./input:/plugin/input:z
networks:
  cluster_network:
