version: '3.2'
services:
  uperf:
    image: quay.io/cloud-bulldozer/uperf
    command: cp /usr/bin/uperf /uperf
    volumes:
      - uperf:/uperf
  plugin:
    image: arcaflow-uperf
    command: "-s uperf -f /plugin/input/netperf.yaml"
    build: .
    networks:
      - cluster_network
    links:
      - "server"
    depends_on:
      - "server"
    volumes:
      - ./input:/plugin/input:z
      - uperf:/uperf
  server:
    image: arcaflow-uperf
    command: "-s uperf_server -f /plugin/input/server_input.yaml"
    build: .
    ports:
      - 20000:20000
    networks:
      - cluster_network
    volumes:
      - ./input:/plugin/input:z
      - uperf:/uperf
networks:
  cluster_network:
volumes:
  uperf: